name: Package UPM project and deploy

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string
    outputs:
      packageversion:
        description: "Returns the version of Unity the UPM package requires"
        value: ${{ jobs.packageRelease.outputs.packageversion }}
jobs:
  packageRelease:
    name: Package UPM Project and tag
    runs-on: ${{ inputs.build-target }}
    outputs:
      packageversion: ${{ steps.getpackageversion.outputs.packageversion }}    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          clean: true
      - uses: actions/setup-node@v2
      - id: getpackageversion
        name: Bump UPM Package version
        run: |
          $result = npm version prerelease -m "Auto increment pre-release version to %s [skip ci]" --force
          echo "::set-output name=packageversion::$result"
      - name: Create Pull Request
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git commit -am "Version release and up version"
          git push
        shell: pwsh
      - name: Create Tag Release
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"        
          git tag -fa "${{ steps.getpackageversion.outputs.packageversion }}" "${GITHUB_SHA}" -m "${{ steps.getpackageversion.outputs.packageversion }}"
          git push origin "${{ steps.getpackageversion.outputs.packageversion }}"
